--[[
   {{GAME_TITLE}}
   Auto-generated by GG AI Memory Hunter
   Generated at: {{GENERATED_AT}}
--]]

local base = nil
local ranges = gg.getRangesList()
for i, v in ipairs(ranges) do
    if v.name:find("{{MODULE_PATTERN}}") then base = v.start; break end
end
if base == nil then
    gg.alert("ไม่พบ {{MODULE_PATTERN}} กรุณาเปิดเกมก่อนรันสคริปต์")
    return
end

{{OFFSETS}}
{{ADDRS}}

while true do
    local items = {
        "เปิดโปรทั้งหมด",
        "ปิดโปร (คืนค่าปกติ)",
        "ออกจากสคริปต์"
    }

    local choice = gg.choice(items, nil, "--- {{GAME_TITLE}} ---")
    if choice == nil or choice == 3 then
        gg.toast("ปิดสคริปต์")
        break
    end

    if choice == 1 then
        local item = {
{{ON_ITEMS}}
        }
        gg.clearList()
        gg.addListItems(item)
        gg.setValues(item)
        gg.alert("เปิดใช้งานโปรทั้งหมดแล้ว")
    elseif choice == 2 then
        local item = {
{{OFF_ITEMS}}
        }
        gg.clearList()
        gg.addListItems(item)
        gg.setValues(item)
        gg.toast("คืนค่าปกติแล้ว")
    end
end
