--[[
   {{GAME_TITLE}}
   Auto-generated by GG AI Memory Hunter
   Generated at: {{GENERATED_AT}}
--]]

local base = nil
local ranges = gg.getRangesList()
for i, v in ipairs(ranges) do
    if v.name:find("{{MODULE_PATTERN}}") then base = v.start; break end
end
if not base then gg.alert("ไม่พบ {{MODULE_PATTERN}}"); return end

local addr = base + {{OFFSET}}
local vals = { {{VALUES}} }
local labels = {
    {{LABELS}}
}

local choice = gg.choice(labels, "เลือกค่าที่ต้องการ")
if choice == nil then
    gg.toast("ยกเลิกการทำงาน")
    return
end

gg.toast("กำลังตั้งค่า...")
gg.sleep(500)
gg.setValues({
    {address = addr, flags = {{FLAG}}, value = vals[choice], freeze = false}
})
gg.alert("ตั้งค่าเป็น: " .. tostring(vals[choice]))
