--[[
   {{GAME_TITLE}}
   Auto-generated by GG AI Memory Hunter
   Generated at: {{GENERATED_AT}}
--]]

local items = {
    "{{ON_LABEL}}",
    "{{OFF_LABEL}}",
    "ออกจากสคริปต์"
}

local choice = gg.choice(items, nil, "--- {{GAME_TITLE}} ---")
if choice == nil or choice == 3 then return end

local base = nil
local ranges = gg.getRangesList()
for i, v in ipairs(ranges) do
    if v.name:find("{{MODULE_PATTERN}}") then
        base = v.start
        break
    end
end

if base == nil then
    gg.alert("ไม่พบ {{MODULE_PATTERN}} กรุณาเปิดเกมก่อนรันสคริปต์")
    return
end

local target_addr = base + {{OFFSET}}
local item = {}
item[1] = {
    address = target_addr,
    flags = {{FLAG}},
    value = choice == 1 and {{ON_VALUE}} or {{OFF_VALUE}},
    freeze = choice == 1 and {{FREEZE_ON}} or false,
    name = choice == 1 and "{{ON_LABEL}}" or "{{OFF_LABEL}}"
}

gg.clearList()
gg.addListItems(item)
gg.setValues(item)

if choice == 1 then
    gg.alert("เปิดใช้งานสำเร็จ\nAddress: " .. string.format("0x%X", target_addr))
else
    gg.alert("คืนค่าปกติเรียบร้อยแล้ว")
end
